In [1]:
import numpy as np

y_predicted=np.array([1,1,0,0,1])
y_true=np.array([0.30,0.7,1,0,0.5])

Mean absolute error
We used for loop

In [10]:
def mae(y_true, y_predicted):
    total_error = 0
    for yt,yp in zip(y_true, y_predicted):
        total_error+=abs(yt-yp)
    print("Total error so far: ", total_error)
    mae= total_error/len(y_true)
    print("Mean Absolute Error: ", mae)
    return mae

In [11]:
mae(y_true, y_predicted)

Total error so far:  2.5
Mean Absolute Error:  0.5


0.5

But we can directly use numpy's functions to do it

In [14]:
np.mean(np.abs(y_predicted-y_true))

0.5

Binary crossentropy


In [27]:

np.log([0])#gives an error because log(0) is undefined

C:\Users\SUBHRADIP\AppData\Local\Temp\ipykernel_8088\3847581346.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])#gives an error because log(0) is undefined


array([-inf])

In [28]:

epsilon = 1e-15

In [29]:

np.log([1e-15])

array([-34.53877639])

In [30]:
y_predicted

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

In [31]:

y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [32]:

1-epsilon

0.999999999999999

In [33]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [34]:

y_predicted_new = np.array(y_predicted_new)

In [35]:

np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [36]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

all together

In [38]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [39]:
log_loss(y_true, y_predicted)

17.2696280766844