In [1]:
import numpy as np

In [2]:
revnue = np.array([[180, 200, 220],[24,36,40],[12,18,20]])
expenses = np.array([[80, 90, 100],[10, 16, 20],[8, 10, 10]])

In [3]:
profit = revnue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [5]:
price_per_unit = np.array([1000, 400, 1200])
units = np.array([[30, 40, 50],[5,10,15],[2,5,7]])

In [ ]:
price_per_unit* units # numpy broadcasting

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [8]:
np.dot( price_per_unit, units)

array([34400, 50000, 64400])

Exercise

In [9]:
revenue1=np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])

In [12]:
inr=revenue1 * 75

In [13]:
inr

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

Exercise2

In [14]:
flower = np.array([[50,60,25],[10,13,5],[40,70,52]]) 

In [15]:
roses=20
lotus=30
sunflower=15

In [26]:
f1 = flower[0,0]*roses + flower[1,0]*lotus + flower[2,0]*sunflower  # roses + lotus + sunflowers in Month 1
# For Month 2
f2 = flower[0,1]*roses + flower[1,1]*lotus + flower[2,1]*sunflower
# For Month 3
f3 = flower[0,2]*roses + flower[1,2]*lotus + flower[2,2]*sunflower

In [27]:
f1

1900

In [28]:

f2

2640

In [29]:
f3

1430